### ISSUE TITLE
ncurses dev files dependency not documented [debian 9]

### ISSUE THREAD

**Issue by Grimeh** [google/ced#2]
If `libncurses5-dev` is not installed the build will fail with:
```
:: bazel build //:ced
INFO: Analysed target //:ced (0 packages loaded).
INFO: Found 1 target...
ERROR: /home/brandon/dev/ced/BUILD:126:1: C++ compilation of rule '//:ced' failed (Exit 1)
main.cc:14:10: fatal error: 'curses.h' file not found
#include <curses.h>
         ^~~~~~~~~~
1 error generated.
Target //:ced failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 5.587s, Critical Path: 2.06s
FAILED: Build did NOT complete successfully
```

After installing the package it builds fine.
This dependency is not documented anywhere (afaict).

**Comment by ctiller** [comment]
Zomg someone tried this.

Yeah the dependency isn't documented anywhere... I'm actually debating whether I can get rid of it.
It'd be nice to be able to just name all the dependencies in the Bazel workspace and keep the build totally hermetic, and ncurses is really hard to get building in that environment - whereas it seems like I could just embed something like https://github.com/nsf/termbox and be happy forever.

**Comment by Grimeh** [comment]
The idea behind the ced is very appealing, so I wanted to try it out early! I haven't had much time to spend trying it out yet though, waiting until holidays to give it a proper go.

Yeah if you want all the dependencies covered by Bazel, then I guess ncurses is not great to that end. Well I see the readme has been updated with dependencies, so I will close this issue.

However since I have your attention :) it looks like ced uses compile commands with libclang for it's features beyond text editing. Is there a specific workflow for getting that setup for an existing project, or is it auto generating compile commands for Bazel projects?
